adminapplication/urls.py
from django.contrib import admin
from django.urls import path
from adminapplication import views
from django.conf import settings
from django.conf.urls.static import static
app_name="adminapplication"

urlpatterns = [
        path('all_orders/', views.all_orders,name='all_orders'),
        path('adminhome/',views.admin_home, name='admin_home'),
        path('viewcat/',views.category_list, name='category_list'),
        path('viewitem/',views.item_list, name='item_list'),
        path('deadstock_item_list/', views.deadstock_item_list, name='deadstock_item_list'),
        path('addcat/',views.add_category, name='add_category'),
        path('add_item/', views.add_item, name='add_item'),
        path('edit_category/<int:category_id>/',views.edit_category, name='edit_category'),
        path('edit_item/<int:item_id>/', views.edit_item, name='edit_item'),
        path('delete_category/<int:category_id>/',views.delete_category, name='delete_category'),
        path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
        path('delete_deadstock_item/<int:deadstock_item_id>/', views.delete_deadstock_item, name='delete_deadstock_item'),
        path('edit_deadstock_item/<int:deadstock_item_id>/', views.edit_deadstock_item, name='edit_deadstock_item'),
        path('add_deadstock_item/', views.add_deadstock_item, name='add_deadstock_item'),
        path('adminlogin/',views.Login_User, name='Login_User'),
        path('logout/', views.user_logout, name="user_logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.contrib import admin
from django.urls import path


# from .views import add_to_cart,cart_api_view,cart_delete,reduce_cart_quantity,get_cart_list,AddOrder,order_items
from .views import  AddToCartAPIView,CartRemoveAPIView,CartViewAPIView,CartDeleteAPIView,get_cart_list,ViewOrdersAPIView,OrderItemsAPIView,BuyItemView


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('add_to_cart/', AddToCartView.as_view(), name='add-to-cart'),
    # path('add_to_cart/<int:item_id>/', add_to_cart, name='add_to_cart'),
    # path('cart-api/', cart_api_view, name='cart-api'),
    # path('delete/<int:b>/', cart_delete, name='cart-delete'),
    # path('reduce_quantity/<int:b>/', reduce_cart_quantity, name='reduce-cart-quantity'),
    # path('list/', get_cart_list, name='cart-list'),
    path('add-to-cart/<int:b>/', AddToCartAPIView.as_view(), name='add_to_cart'),
    path('cart-remove/<int:b>/', CartRemoveAPIView.as_view(), name='cart_remove'),
    path('cart-view/', CartViewAPIView.as_view(), name='cart_view'),
    path('cart-delete/<int:b>/', CartDeleteAPIView.as_view(), name='cart_delete'),
    path('list/', get_cart_list, name='cart-list'),
    # path('orderitems/<int:id>/',AddOrder,name='order_items'),
    # path('order/<int:id>/',order_items),
    # path('CartOrderAPIView/', CartOrderAPIView.as_view(), name='CartOrderAPIView'),
    path('api/order-items/', OrderItemsAPIView.as_view(), name='order_items_api'),
    path('view-orders/', ViewOrdersAPIView.as_view(), name='view_orders'),
    path('buy/<int:item_id>/', BuyItemView.as_view(), name='buy_item'),
]

spare_part_management/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_spectacular.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('owner.urls')),
    path("user/",include('user.urls')),
    path("admin1/",include('adminapplication.urls')),
    path("cart/",include('cart.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('schema/docs/', SpectacularSwaggerView.as_view(url_name='schema')),
    # path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

templates/add_cat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Category</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">Upload Category</h3>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" class="p-4">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="category_name" class="form-label">Category Name</label>
                            <input type="text" class="form-control" id="category_name" name="category_name" placeholder="Enter category name" required>
                        </div>
                        <div class="form-group">
                            <label for="category_image" class="form-label">Category Image</label>
                            <div class="input-group">
                                <input type="file" class="form-control" id="category_image" name="category_image" accept="image/*" required>
                                <label class="input-group-text" for="category_image">Choose file</label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap JS and dependencies -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/add_deadstock_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Deadstock Item</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        h1 {
            color: #333;
            text-align: center;
        }

        form {
            max-width: 600px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="number"],
        textarea,
        select {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="checkbox"] {
            margin-right: 5px;
        }

        input[type="file"] {
            margin-top: 5px;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h1>Add Deadstock Item</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="deadstock_item">Item Name:</label>
        <input type="text" id="deadstock_item" name="deadstock_item" required><br>

        <label for="price">Price:</label>
        <input type="text" id="price" name="price" required><br>

        <label for="description">Description:</label>
        <textarea id="description" name="description" required></textarea><br>

        <label for="stock">Stock:</label>
        <input type="number" id="stock" name="stock" required><br>

        <input type="checkbox" id="available" name="available" checked>
        <label for="available">Available</label><br>

        <label for="manufacturer">Manufacturer:</label>
        <input type="text" id="manufacturer" name="manufacturer" required><br>

        <label for="item_image">Item Image:</label>
        <input type="file" id="item_image" name="item_image" required><br>

        <input type="submit" value="Add Deadstock Item">
    </form>
</body>
</html>

templates/admin_home.html
{% extends 'admin_navigation.html' %}
{% load static %}
{% block body %}

<div class="market-updates">
    <a href="{% url 'adminapplication:category_list' %}">
        <div class="col-md-4 market-update-gd">
            <div class="market-update-block clr-block-1" style="background-color: blue;">
                <div class="col-md-8 market-update-left">
                    <h3></h3>
                    <h4>All Categories</h4>
                    <p></p>
                </div>
                <div class="col-md-4 market-update-right">
                    <i style="border-radius: 50%; font-size: 45px; color: Lime; background: white; padding: 18px;" class="fas fa-cog"> </i>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </a>
    <a href="{% url 'adminapplication:item_list' %}">
        <div class="col-md-4 market-update-gd">
            <div class="market-update-block clr-block-2" style="background-color: blue;">
                <div class="col-md-8 market-update-left">
                    <h3></h3>
                    <h4>All Items</h4>
                    <p></p>
                </div>
                <div class="col-md-4 market-update-right">
                    <i class="fa fa-eye"> </i>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </a>
    <a href="{% url 'adminapplication:deadstock_item_list' %}">
        <div class="col-md-4 market-update-gd">
            <div class="market-update-block clr-block-3">
                <div class="col-md-8 market-update-left">
                    <h3></h3>
                    <h4>All deadstock items</h4>
                    <p></p>
                </div>
                <div class="col-md-4 market-update-right">
                    <i class="fa fa-envelope-o"> </i>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </a>
    <div class="clearfix"> </div>
</div>
<footer class="site-footer" style="margin-top: 15%;">
    <div class="container">
        <!-- Footer content here -->
    </div>
</footer>

{% endblock %}

templates/admin_navigation.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
<title>Home Service</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Shoppy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<link href="{% static 'admin home/css2/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
<!-- Custom Theme files -->
<link href="{% static 'admin home/css2/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
<!--js-->
<script src="{% static 'admin home/js2/jquery-2.1.1.min.js' %}"></script>
<!--icons-css-->
<link href="{% static 'admin home/css2/font-awesome.css' %}" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!--Google Fonts-->
<link href='//fonts.googleapis.com/css?family=Carrois+Gothic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Work+Sans:400,500,600' rel='stylesheet' type='text/css'>
<!--static chart-->
<script src="{% static 'admin home/js2/Chart.min.js' %}"></script>
<!--//charts-->
<!-- geo chart -->
    <script src="//cdn.js' %}delivr.net/modernizr/2.8.3/modernizr.min.js' %}" type="text/javascript"></script>
    <script>window.modernizr || document.write('<script src="lib/modernizr/modernizr-custom.js' %}"><\/script>')</script>
    <!--<script src="lib/html5shiv/html5shiv.js' %}"></script>-->
     <!-- Chartinator  -->
    <script src="{% static 'admin home/js2/chartinator.js' %}" ></script>
    <script type="text/javascript">
        jQuery(function ($) {

            var chart3 = $('#geoChart').chartinator({
                tableSel: '.geoChart',

                columns: [{role: 'tooltip', type: 'string'}],

                colIndexes: [2],

                rows: [
                    ['China - 2015'],
                    ['Colombia - 2015'],
                    ['France - 2015'],
                    ['Italy - 2015'],
                    ['Japan - 2015'],
                    ['Kazakhstan - 2015'],
                    ['Mexico - 2015'],
                    ['Poland - 2015'],
                    ['Russia - 2015'],
                    ['Spain - 2015'],
                    ['Tanzania - 2015'],
                    ['Turkey - 2015']],

                ignoreCol: [2],

                chartType: 'GeoChart',

                chartAspectRatio: 1.5,

                chartZoom: 1.75,

                chartOffset: [-12,0],

                chartOptions: {

                    width: null,

                    backgroundColor: '#fff',

                    datalessRegionColor: '#F5F5F5',

                    region: 'world',

                    resolution: 'countries',

                    legend: 'none',

                    colorAxis: {

                        colors: ['#679CCA', '#337AB7']
                    },
                    tooltip: {

                        trigger: 'focus',

                        isHtml: true
                    }
                }


            });
        });
    </script>
<!--geo chart-->

<!--skycons-icons-->
<script src="{% static 'admin home/js2/skycons.js' %}"></script>
<!--//skycons-icons-->
	<style>
.glow {
  font-size: 80px;
  color: #fff;
  text-align: center;
  -webkit-animation: glow 1s ease-in-out infinite alternate;
  -moz-animation: glow 1s ease-in-out infinite alternate;
  animation: glow 1s ease-in-out infinite alternate;
}

@-webkit-keyframes glow {
  from {
    text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #e60073, 0 0 40px #e60073, 0 0 50px #e60073, 0 0 60px #e60073, 0 0 70px #e60073;
  }

  to {
    text-shadow: 0 0 20px #fff, 0 0 30px #ff4da6, 0 0 40px #ff4da6, 0 0 50px #ff4da6, 0 0 60px #ff4da6, 0 0 70px #ff4da6, 0 0 80px #ff4da6;
  }
}

/* Rounded border */
hr.rounded {
  border-top: 8px solid lightblue;
  border-radius: 5px;
}

.prjdiv:hover{
transform:translateY(-10px)
}
div .container1{

width:100%;
background-color:white;
border-radius:8px;
}
h2, h4{
 padding:10Px;
}

</style>
</head>
<body>
<div class="page-container" >
   <div class="left-content">
	   <div class="mother-grid-inner">
            <!--header start here-->
				<div class="header-main" style="background-color:;">
					<div class="header-left">
							<div class="logo-name" style="width:100%">
								<h1><span>Spare Parts Admin </span></h1>
							</div>
							<!--search-box-->

							<div class="clearfix"> </div>
						 </div>


							<!--notification menu end -->
							<div class="profile_details">
								<ul>
									<li class="dropdown profile_details_drop">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
											<div align class="profile_img">

												<div class="user-name">
													<p>{{request.user.username}}</p>
													<span>Hi,Admin</span>
												</div>
												<i class="fa fa-angle-down lnr"></i>
												<i class="fa fa-angle-up lnr"></i>
												<div class="clearfix"></div>
											</div>
										</a>
										<ul class="dropdown-menu drp-mnu">

											<li> <a href="{% url 'adminapplication:user_logout' %}"><i class="fa fa-sign-out"></i> Logout</a> </li>
										</ul>
									</li>
								</ul>
							</div>
							<div class="clearfix"> </div>
						</div>
				     <div class="clearfix"> </div>
				</div>
<!--heder end here-->
<!-- script-for sticky-nav -->
		<script>
		$(document).ready(function() {
			 var navoffeset=$(".header-main").offset().top;
			 $(window).scroll(function(){
				var scrollpos=$(window).scrollTop();
				if(scrollpos >=navoffeset){
					$(".header-main").addClass("fixed");
				}else{
					$(".header-main").removeClass("fixed");
				}
			 });

		});
		</script>
		<!-- /script-for sticky-nav -->
<!--inner block start here-->
<div class="inner-block" style="padding-top:8%">
<!--market updates updates-->
	{% block body %}
	{% endblock %}
</div>
<!--inner block end here-->

</div>
</div>
<!--slider menu-->
    <div class="sidebar-menu">
		  	<div class="logo"> <a href="#" class="sidebar-icon">
				<span class="fa fa-bars"></span> </a>
				<a href="#"> <span id="logo"></span>
			      <!--<img id="logo" src="" alt="Logo"/>-->
			  </a> </div>
		    <div class="menu">
		      <ul id="menu">
		        <li id="menu-home"><a href=""><i class="fa fa-tachometer"></i><span>Dashboard</span></a></li>
		        <li><a href="#"><i class="fa fa-cogs"></i><span>Dead Stock</span><span class="fa fa-angle-right" style="float: right"></span></a>
		          <ul>
		            <li><a href="{% url 'adminapplication:add_deadstock_item' %}">Add deadstock Items</a></li>
		            <li><a href="{% url 'adminapplication:deadstock_item_list' %}">view deadstock Items</a></li>
		          </ul>
		        </li>
		        <li id="menu-comunicacao" ><a href="#"><i class="fa fa-users"></i><span>Items</span><span class="fa fa-angle-right" style="float: right"></span></a>
		          <ul id="menu-comunicacao-sub" >
		            <li id="menu-mensagens" style="width: 120px" ><a href="{% url 'adminapplication:add_item' %}">Add Items</a>
		            </li>
					  <li id="menu-mensagens" style="width: 120px" ><a href="{% url 'adminapplication:item_list' %}">view Items</a>
		            </li>
		          </ul>
		        </li>
		        <li id="menu-academico" ><a href="#"><i class="fa fa-file-text"></i><span>Categories</span><span class="fa fa-angle-right" style="float: right"></span></a>
		          <ul id="menu-academico-sub" >
		          	 <li id="menu-academico-boletim" ><a href="{% url 'adminapplication:add_category' %}">Add categories</a></li>
		            <li id="menu-academico-avaliacoes" ><a href="{% url 'adminapplication:category_list' %}">View categories</a></li>
		          </ul>
		        </li>
				  <li><a href="{% url 'adminapplication:all_orders' %}"><i class="fa fa-car">
				</i><span>View Order</span></a></li>








		      </ul>
		    </div>
	 </div>
	<div class="clearfix"> </div>
</div>
<!--slide bar menu end here-->
<script>
var toggle = true;

$(".sidebar-icon").click(function() {
  if (toggle)
  {
    $(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
    $("#menu span").css' %}({"position":"absolute"});
  }
  else
  {
    $(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
    setTimeout(function() {
      $("#menu span").css' %}({"position":"relative"});
    }, 400);
  }
                toggle = !toggle;
            });
</script>
<!--scrolling js-->
		<script src="{% static 'admin home/js2/jquery.nicescroll.js' %}"></script>
		<script src="{% static 'admin home/js2/scripts.js' %}"></script>
		<!--//scrolling js-->
<script src="{% static 'admin home/js2/bootstrap.js' %}"> </script>
<!-- mother grid end here-->
</body>
</html>

templates/deadstock_item_list.html
<style>
    table {
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
    }

    th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f2f2f2;
    }

    img {
        display: block;
        max-width: 100%;
        height: auto;
    }
</style>



<table class="table">
    <thead>
        <tr>
            <th>Item Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Stock</th>
<!--            <th>Available</th>-->
            <th>Manufacturer</th>
            <th>Item Image</th>
            <th>Edit</th>
            <th>Delete</th>
            <th><a href="{% url 'adminapplication:admin_home' %}" class="btn btn-warning">Admin Home</a></th>
        </tr>
    </thead>
    <tbody>
        {% for deadstock_item in deadstock_items %}
        <tr>
            <td>{{ deadstock_item.deadstock_item }}</td>
            <td>{{ deadstock_item.price }}</td>
            <td>{{ deadstock_item.description }}</td>
            <td>{{ deadstock_item.stock }}</td>
<!--            <td>{{ deadstock_item.available }}</td>-->
            <td>{{ deadstock_item.manufacturer }}</td>
            <td>
                {% if deadstock_item.item_image %}
                <img src="{{ deadstock_item.item_image.url }}" style="max-height: 200px; max-width: 200px;" alt="{{ deadstock_item.deadstock_item }}">
                {% else %}
                No Image Available
                {% endif %}
            </td>
            <td>
                <a href="{% url 'adminapplication:edit_deadstock_item' deadstock_item.id %}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <a href="{% url 'adminapplication:delete_deadstock_item' deadstock_item.id %}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/delete_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Category</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        h1 {
            color: #333;
            text-align: center;
        }

        p {
            text-align: center;
            margin-bottom: 20px;
        }

        form {
            max-width: 300px;
            margin: 0 auto;
            text-align: center;
        }

        input[type="submit"] {
            background-color: #ff5733;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #e64a19;
        }
    </style>
</head>
<body>
    <h1>Delete Category</h1>
    <p>Are you sure you want to delete the category "{{ category.category_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
</body>
</html>

templates/delete_deadstock_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Deadstock Item</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        h1 {
            color: #333;
            text-align: center;
        }

        p {
            text-align: center;
            margin-bottom: 20px;
        }

        form {
            max-width: 300px;
            margin: 0 auto;
            text-align: center;
        }

        input[type="submit"] {
            background-color: #ff5733;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #e64a19;
        }
    </style>
</head>
<body>
    <h1>Delete Deadstock Item</h1>
    <p>Are you sure you want to delete the Deadstock Item "{{ deadstock_item.deadstock_item }}"?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
</body>
</html>

templates/item_list.html
<style>
    table {
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
    }

    th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f2f2f2;
    }

    img {
        display: block;
        max-width: 100%;
        height: auto;
    }
</style>

<table class="table">
    <thead>
        <tr>
            <th>Item Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Stock</th>
<!--            <th>Available</th>-->
            <th>Category</th>
            <th>Manufacturer</th>
            <th>Item Image</th>
            <th>Edit</th>
            <th>Delete</th>
            <th><a href="{% url 'adminapplication:admin_home' %}" class="btn btn-warning">Admin Home</a></th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.item_name }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.stock }}</td>
<!--            <td>{{ item.available }}</td>-->
            <td>{{ item.category.category_name }}</td>
            <td>{{ item.manufacturer }}</td>
            <td>
                {% if item.item_image %}
                <img src="{{ item.item_image.url }}" style="max-height: 200px; max-width: 200px;" alt="{{ item.item_name }}">
                {% else %}
                No Image Available
                {% endif %}
            </td>
            <td>
                <a href="{% url 'adminapplication:edit_item' item.id %}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <a href="{% url 'adminapplication:delete_item' item.id %}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/view_cat.html
<style>
    table {
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
    }

    th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f2f2f2;
    }

    img {
        display: block;
        max-width: 100%;
        height: auto;
    }
</style>

<table>
    <thead>
        <tr>
            <th>Category Name</th>
            <th>Category Image</th>
            <th>Edit Category</th>
            <th>Delete</th>
            <th><a href="{% url 'adminapplication:admin_home' %}" class="btn btn-warning">admin</a></th>
        </tr>
    </thead>
    <tbody>
        {% for i in categories %}
        <tr>
            <td>{{i.category_name}}</td>
            <td>
                <img src="{{i.category_image.url}}" style="height:200px;width:25%" alt="{{i.category_name}}">
            </td>
            <td>
               <a href="{% url 'adminapplication:edit_category' i.id %}">Edit Category</a>
                </td>
            <td>
               <a href="{% url 'adminapplication:delete_category' i.id %}" class="btn btn-warning">delete</a>
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>